import { EntityManager } from '@mikro-orm/core';
import { Seeder } from '@mikro-orm/seeder';
import { Player } from '../entities/Player';

export class PlayerSeeder extends Seeder {
  async run(em: EntityManager): Promise<void> {
    const playerList = [
  { name: 'Baby Luigi' },
  { name: 'Baby Peach' },
  { name: 'Baby Mario' },
  { name: 'Yellow Toad' },
  { name: 'Toad' },
  { name: 'Blue Toad' },
  { name: 'Purple Toad' },
  { name: 'Green Toad' },
  { name: 'Goomba' },
  { name: 'Baby Daisy' },
  { name: 'Blooper' },
  { name: 'Monty Mole' },
  { name: 'Red Noki' },
  { name: 'Blue Noki' },
  { name: 'Green Noki' },
  { name: 'Toadette' },
  { name: 'Boo' },
  { name: 'Blue Yoshi' },
  { name: 'Red Yoshi' },
  { name: 'Light Blue Yoshi' },
  { name: 'Pink Yoshi' },
  { name: 'Yellow Yoshi' },
  { name: 'Paratroopa' },
  { name: 'Green Paratroopa' },
  { name: 'Gray Shy Guy' },
  { name: 'Blue Shy Guy' },
  { name: 'Yellow Shy Guy' },
  { name: 'Green Shy Guy' },
  { name: 'Shy Guy' },
  { name: 'Red Koopa' },
  { name: 'Koopa' },
  { name: 'Dixie Kong' },
  { name: 'Toadsworth' },
  { name: 'Paragoomba' },
  { name: 'Yellow Pianta' },
  { name: 'Red Pianta' },
  { name: 'Blue Pianta' },
  { name: 'Baby DK' },
  { name: 'Tiny Kong' },
  { name: 'Green Magikoopa' },
  { name: 'Blue Magikoopa' },
  { name: 'Red Magikoopa' },
  { name: 'Yellow Magikoopa' },
  { name: 'Green Dry Bones' },
  { name: 'Dry Bones' },
  { name: 'Blue Dry Bones' },
  { name: 'Dark Bones' },
  { name: 'Hammer Bro' },
  { name: 'Fire Bro' },
  { name: 'Boomerang Bro' },
  { name: 'King Boo' },
  { name: 'Diddy Kong' },
  { name: 'Wiggler' },
  { name: 'Blue Kritter' },
  { name: 'Kritter' },
  { name: 'Brown Kritter' },
  { name: 'Red Kritter' },
  { name: 'Peach' },
  { name: 'Wario' },
  { name: 'Waluigi' },
  { name: 'Bowser Jr.' },
  { name: 'Yoshi' },
  { name: 'Daisy' },
  { name: 'Birdo' },
  { name: 'Luigi' },
  { name: 'Mario' },
  { name: 'Funky Kong' },
  { name: 'Bowser' },
  { name: 'King K. Rool' },
  { name: 'Donkey Kong' },
  { name: 'Petey Piranha' }
];


    for (const p of playerList) {
      em.create(Player, p);
    }
  }
}