import { EntityManager } from '@mikro-orm/core';
import { Seeder } from '@mikro-orm/seeder';
import { Player } from '../entities/Player.js';

export class PlayerSeeder extends Seeder {
  async run(em: EntityManager): Promise<void> {
const playerList = [
  { name: 'Baby Luigi', profilePictureUrl: 'https://mario.wiki.gallery/images/2/2f/MSS_Baby_Luigi_Character_Select_Mugshot.png' },
  { name: 'Baby Peach', profilePictureUrl: 'https://mario.wiki.gallery/images/6/66/MSS_Baby_Peach_Character_Select_Mugshot.png' },
  { name: 'Baby Daisy', profilePictureUrl: 'https://mario.wiki.gallery/images/4/44/MSS_Baby_Daisy_Character_Select_Mugshot.png' },
  { name: 'Baby Donkey Kong', profilePictureUrl: 'https://mario.wiki.gallery/images/d/d0/MSS_Baby_Donkey_Kong_Character_Select_Mugshot.png' },
  { name: 'Baby Mario', profilePictureUrl: 'https://mario.wiki.gallery/images/d/d6/MSS_Baby_Mario_Character_Select_Mugshot.png' },
  { name: 'Birdo', profilePictureUrl: 'https://mario.wiki.gallery/images/b/b2/MSS_Birdo_Character_Select_Mugshot.png' },
  { name: 'Blooper', profilePictureUrl: 'https://mario.wiki.gallery/images/1/15/MSS_Blooper_Character_Select_Mugshot.png' },
  { name: 'Boo', profilePictureUrl: 'https://mario.wiki.gallery/images/b/b7/MSS_Boo_Character_Select_Mugshot.png' },
  { name: 'Bowser', profilePictureUrl: 'https://mario.wiki.gallery/images/8/82/MSS_Bowser_Character_Select_Mugshot.png' },
  { name: 'Bowser Jr.', profilePictureUrl: 'https://mario.wiki.gallery/images/c/c5/MSS_Bowser_Jr_Character_Select_Mugshot.png' },
  { name: 'Daisy', profilePictureUrl: 'https://mario.wiki.gallery/images/f/f6/MSS_Daisy_Character_Select_Mugshot.png' },
  { name: 'Dark Bones', profilePictureUrl: 'https://mario.wiki.gallery/images/f/fd/MSS_Dark_Bones_Character_Select_Mugshot.png' },
  { name: 'Diddy Kong', profilePictureUrl: 'https://mario.wiki.gallery/images/1/1a/MSS_Diddy_Kong_Character_Select_Mugshot.png' },
  { name: 'Dixie Kong', profilePictureUrl: 'https://mario.wiki.gallery/images/6/65/MSS_Dixie_Kong_Character_Select_Mugshot.png' },
  { name: 'Donkey Kong', profilePictureUrl: 'https://mario.wiki.gallery/images/a/a7/MSS_Donkey_Kong_Character_Select_Mugshot.png' },
  { name: 'Dry Bones', profilePictureUrl: 'https://mario.wiki.gallery/images/b/bb/MSS_Dry_Bones_Character_Select_Mugshot.png' },
  { name: 'Green Dry Bones', profilePictureUrl: 'https://mario.wiki.gallery/images/b/bb/MSS_Dry_Bones_Character_Select_Mugshot.png' },
  { name: 'Blue Dry Bones', profilePictureUrl: 'https://mario.wiki.gallery/images/b/bb/MSS_Dry_Bones_Character_Select_Mugshot.png' },
  { name: 'Funky Kong', profilePictureUrl: 'https://mario.wiki.gallery/images/b/bc/MSS_Funky_Kong_Character_Select_Mugshot.png' },
  { name: 'Goomba', profilePictureUrl: 'https://mario.wiki.gallery/images/2/20/MSS_Goomba_Character_Select_Mugshot.png' },
  { name: 'Hammer Bro', profilePictureUrl: 'https://mario.wiki.gallery/images/0/01/MSS_Hammer_Fire_and_Boomerang_Bro_Character_Select_Mugshot.png' },
  { name: 'Fire Bro', profilePictureUrl: 'https://mario.wiki.gallery/images/0/01/MSS_Hammer_Fire_and_Boomerang_Bro_Character_Select_Mugshot.png' },
  { name: 'Boomarang Bro', profilePictureUrl: 'https://mario.wiki.gallery/images/0/01/MSS_Hammer_Fire_and_Boomerang_Bro_Character_Select_Mugshot.png' },
  { name: 'King Boo', profilePictureUrl: 'https://mario.wiki.gallery/images/3/3e/MSS_King_Boo_Character_Select_Mugshot.png' },
  { name: 'Koopa Paratroopa', profilePictureUrl: 'https://mario.wiki.gallery/images/7/73/MSS_Koopa_Paratroopa_Character_Select_Mugshot.png' },
  { name: 'Red Paratroopa', profilePictureUrl: 'https://mario.wiki.gallery/images/7/73/MSS_Koopa_Paratroopa_Character_Select_Mugshot.png' },
  { name: 'Koopa Troopa', profilePictureUrl: 'https://mario.wiki.gallery/images/a/ae/MSS_Koopa_Troopa_Character_Select_Mugshot.png' },
  { name: 'Red Koopa', profilePictureUrl: 'https://mario.wiki.gallery/images/a/ae/MSS_Koopa_Troopa_Character_Select_Mugshot.png' },
  { name: 'Blue Kritter', profilePictureUrl: 'https://mario.wiki.gallery/images/e/e4/MSS_Blue_Kritter_Character_Select_Mugshot.png' },
  { name: 'Brown Kritter', profilePictureUrl: 'https://mario.wiki.gallery/images/0/03/MSS_Brown_Kritter_Character_Select_Mugshot.png' },
  { name: 'Green Kritter', profilePictureUrl: 'https://mario.wiki.gallery/images/b/bc/MSS_Green_Kritter_Character_Select_Mugshot.png' },
  { name: 'Red Kritter', profilePictureUrl: 'https://mario.wiki.gallery/images/2/25/MSS_Red_Kritter_Character_Select_Mugshot.png' },
  { name: 'Luigi', profilePictureUrl: 'https://mario.wiki.gallery/images/2/20/MSS_Luigi_Character_Select_Mugshot.png' },
  { name: 'Blue Magikoopa', profilePictureUrl: 'https://mario.wiki.gallery/images/1/12/MSS_Blue_Magikoopa_Character_Select_Mugshot.png' },
  { name: 'Green Magikoopa', profilePictureUrl: 'https://mario.wiki.gallery/images/3/3b/MSS_Green_Magikoopa_Character_Select_Mugshot.png' },
  { name: 'Red Magikoopa', profilePictureUrl: 'https://mario.wiki.gallery/images/6/67/MSS_Red_Magikoopa_Character_Select_Mugshot.png' },
  { name: 'Yellow Magikoopa', profilePictureUrl: 'https://mario.wiki.gallery/images/b/b2/MSS_Yellow_Magikoopa_Character_Select_Mugshot.png' },
  { name: 'Mario', profilePictureUrl: 'https://mario.wiki.gallery/images/3/36/MSS_Mario_Character_Select_Mugshot.png' },
  { name: 'Monty Mole', profilePictureUrl: 'https://mario.wiki.gallery/images/c/c4/MSS_Monty_Mole_Character_Select_Mugshot.png' },
  { name: 'Blue Noki', profilePictureUrl: 'https://mario.wiki.gallery/images/a/a7/MSS_Blue_Noki_Character_Select_Mugshot.png' },
  { name: 'Green Noki', profilePictureUrl: 'https://mario.wiki.gallery/images/0/06/MSS_Green_Noki_Character_Select_Mugshot.png' },
  { name: 'Red Noki', profilePictureUrl: 'https://mario.wiki.gallery/images/f/f3/MSS_Red_Noki_Character_Select_Mugshot.png' },
  { name: 'Paragoomba', profilePictureUrl: 'https://mario.wiki.gallery/images/9/9d/MSS_Paragoomba_Character_Select_Mugshot.png' },
  { name: 'Peach', profilePictureUrl: 'https://mario.wiki.gallery/images/a/ad/MSS_Peach_Character_Select_Mugshot.png' },
  { name: 'Petey Piranha', profilePictureUrl: 'https://mario.wiki.gallery/images/f/f4/MSS_Petey_Piranha_Character_Select_Mugshot.png' },
  { name: 'Blue Pianta', profilePictureUrl: 'https://mario.wiki.gallery/images/b/b7/MSS_Blue_Pianta_Character_Select_Mugshot.png' },
  { name: 'Red Pianta', profilePictureUrl: 'https://mario.wiki.gallery/images/f/f2/MSS_Red_Pianta_Character_Select_Mugshot.png' },
  { name: 'Yellow Pianta', profilePictureUrl: 'https://mario.wiki.gallery/images/a/a1/MSS_Yellow_Pianta_Character_Select_Mugshot.png' },
  { name: 'Blue Shy Guy', profilePictureUrl: 'https://mario.wiki.gallery/images/b/bd/MSS_Blue_Shy_Guy_Character_Select_Mugshot.png' },
  { name: 'Gray Shy Guy', profilePictureUrl: 'https://mario.wiki.gallery/images/e/e7/MSS_Gray_Shy_Guy_Character_Select_Mugshot.png' },
  { name: 'Green Shy Guy', profilePictureUrl: 'https://mario.wiki.gallery/images/0/0b/MSS_Green_Shy_Guy_Character_Select_Mugshot.png' },
  { name: 'Red Shy Guy', profilePictureUrl: 'https://mario.wiki.gallery/images/1/17/MSS_Red_Shy_Guy_Character_Select_Mugshot.png' },
  { name: 'King K. Rool', profilePictureUrl: 'https://mario.wiki.gallery/images/2/2b/MSS_King_K_Rool_Character_Select_Mugshot.png' },
  { name: 'Yellow Shy Guy', profilePictureUrl: 'https://mario.wiki.gallery/images/5/53/MSS_Yellow_Shy_Guy_Character_Select_Mugshot.png' },
  { name: 'Tiny Kong', profilePictureUrl: 'https://mario.wiki.gallery/images/4/47/MSS_Tiny_Kong_Character_Select_Mugshot.png' },
  { name: 'Blue Toad', profilePictureUrl: 'https://mario.wiki.gallery/images/0/08/MSS_Blue_Toad_Character_Select_Mugshot.png' },
  { name: 'Green Toad', profilePictureUrl: 'https://mario.wiki.gallery/images/c/c1/MSS_Green_Toad_Character_Select_Mugshot.png' },
  { name: 'Purple Toad', profilePictureUrl: 'https://mario.wiki.gallery/images/c/cc/MSS_Purple_Toad_Character_Select_Mugshot.png' },
  { name: 'Red Toad', profilePictureUrl: 'https://mario.wiki.gallery/images/2/2b/MSS_Red_Toad_Character_Select_Mugshot.png' },
  { name: 'Yellow Toad', profilePictureUrl: 'https://mario.wiki.gallery/images/7/7f/MSS_Yellow_Toad_Character_Select_Mugshot.png' },
  { name: 'Toadette', profilePictureUrl: 'https://mario.wiki.gallery/images/b/b9/MSS_Toadette_Character_Select_Mugshot.png' },
  { name: 'Toadsworth', profilePictureUrl: 'https://mario.wiki.gallery/images/5/56/MSS_Toadsworth_Character_Select_Mugshot.png' },
  { name: 'Waluigi', profilePictureUrl: 'https://mario.wiki.gallery/images/a/a5/MSS_Waluigi_Character_Select_Mugshot.png' },
  { name: 'Wario', profilePictureUrl: 'https://mario.wiki.gallery/images/a/ac/MSS_Wario_Character_Select_Mugshot.png' },
  { name: 'Wiggler', profilePictureUrl: 'https://mario.wiki.gallery/images/9/99/MSS_Wiggler_Character_Select_Mugshot.png' },
  { name: 'Yoshi', profilePictureUrl: 'https://mario.wiki.gallery/images/6/60/MSS_Yoshi_Character_Select_Mugshot.png' },
  { name: 'Blue Yoshi', profilePictureUrl: 'https://mario.wiki.gallery/images/e/e7/MSS_Blue_Yoshi_Character_Select_Mugshot.png' },
  { name: 'Light-Blue Yoshi', profilePictureUrl: 'https://mario.wiki.gallery/images/4/49/MSS_Light-Blue_Yoshi_Character_Select_Mugshot.png' },
  { name: 'Pink Yoshi', profilePictureUrl: 'https://mario.wiki.gallery/images/b/b9/MSS_Pink_Yoshi_Character_Select_Mugshot.png' },
  { name: 'Red Yoshi', profilePictureUrl: 'https://mario.wiki.gallery/images/7/7c/MSS_Red_Yoshi_Character_Select_Mugshot.png' },
  { name: 'Yellow Yoshi', profilePictureUrl: 'https://mario.wiki.gallery/images/8/8e/MSS_Yellow_Yoshi_Character_Select_Mugshot.png' }
];


    await em.persistAndFlush(
      playerList.map(p => em.create(Player, p))
    );
  }
}